name: Build and Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths:
    # Changes to the package itself
    - src/msgspec/**
    - pyproject.toml
    - setup.py
    - MANIFEST.in
    # Changes to CI execution
    - .github/workflows/ci.yml
    - .github/workflows/prepare-build.yml
    - .github/workflows/build-wheels.yml
    - .github/actions/latest-supported-python/action.yml
    - .github/actions/fetch-release-history/action.yml
    - .cibuildwheel.toml
    - .justfile
    # Changes to testing
    - tests/**
    - .codecov.yml
    - .codespellrc
    - .coveragerc
    - .pre-commit-config.yaml
    - .pytest.toml
    - .ruff.toml
  release:
    types:
    - published

permissions: {}

env:
  UV_NO_EDITABLE: "true"
  UV_NO_SYNC: "true"

jobs:
  prepare:
    name: Validate build
    uses: ./.github/workflows/prepare-build.yml
    permissions:
      contents: read
    with:
      run-static-analysis: true
      fetch-latest-python: true

  test:
    name: Test Python ${{ matrix.python-version }} on ${{ startsWith(matrix.os, 'macos-') && 'macOS' || startsWith(matrix.os, 'windows-') && 'Windows' || 'Linux' }}
    needs:
    - prepare
    runs-on: "${{ matrix.os }}"
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        # - windows-latest
        # - macos-latest
        python-version:
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
        - "3.15-dev"

    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      with:
        persist-credentials: false

    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
      with:
        python-version: "${{ matrix.python-version }}"

    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
      with:
        enable-cache: false

    - name: Install command runner
      run: uv tool install rust-just

    - name: Install testing dependencies
      env:
        MSGSPEC_SANITIZE: "true"
        MSGSPEC_COVERAGE: "true"
      run: just env-sync test

    - name: Run tests with sanitizers
      env:
        PYTHONMALLOC: "malloc"
        ASAN_OPTIONS: "detect_leaks=0"
      run: >-
        LD_PRELOAD=$(gcc -print-file-name=libasan.so)
        just env-run test coverage run -m pytest tests/unit -s

    - name: Generate coverage files
      run: |-
        just env-run test coverage xml
        find build/temp*/ -name '*.o' -exec gcov -abcu {} +

    - name: Upload coverage artifacts
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4  # v5
      with:
        name: coverage-${{ matrix.python-version }}-${{ matrix.os }}
        path: |-
          coverage.xml
          _core.c.gcov
          atof.h.gcov
          ryu.h.gcov
        if-no-files-found: error

  upload-coverage:
    name: Upload coverage files to Codecov
    needs:
    - test
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      with:
        persist-credentials: false

    - name: Download coverage artifacts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0  # v5
      with:
        pattern: coverage-*
        path: coverage-files

    - name: See the coverage files
      run: tree -sh coverage-files

    - name: Upload Codecov
      uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac  # v5
      with:
        use_oidc: true
        directory: coverage-files

  test-integration:
    name: Run integration tests
    needs:
    - test
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5
      with:
        persist-credentials: false

    - name: Install Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
      with:
        python-version-file: pyproject.toml

    - name: Install uv
      uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78  # v7
      with:
        enable-cache: false

    - name: Install command runner
      run: uv tool install rust-just

    - name: Install testing dependencies
      run: just env-sync test

    - name: Run doctests
      run: just test-doc

    - name: Run type checker compatibility tests
      run: just test-typing

  build-wheels:
    name: Build wheels ${{ github.event_name == 'release' && 'for release' || '' }}
    needs:
    - test
    - prepare
    uses: ./.github/workflows/build-wheels.yml
    permissions:
      actions: read
      contents: read
    with:
      sdist-name: "${{ needs.prepare.outputs.sdist-name }}"
      build-all: ${{ github.event_name == 'release' }}

  upload-pypi:
    name: Upload artifacts to PyPI
    if: github.event_name == 'release' && github.event.action == 'published'
    needs:
    - prepare
    - build-wheels
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write

    steps:
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53  # v6
      with:
        pattern: artifact-*
        merge-multiple: true
        path: dist

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # release/v1
